### ISSUE TITLE
Sinker docker image?

### ISSUE THREAD

**Issue by OmegaVVeapon** [plexsystems/sinker#29]
Hello!

I started playing with Sinker today and it's great, definitely what we need for our use case.

However, I wanted to use it as part of our CI pipelines to keep project images synced to our internal registries and I can't find a Sinker Docker image anywhere... before I rolled out my own I wanted to ask, does it already exist somewhere?

**Comment by OmegaVVeapon** [comment]
Done.

@jpreese Please let me know if there's any changes needed in the PR discussion.

**Comment by eik3** [comment]
Thanks for the Dockerfile! `sinker` works great and I'd like to start using it from Kubernetes.

If this issue is about an official sinker docker image in a public registry, I'm confused why it's closed - I looked around in a couple of registries and didn't find one. There's also no workflow yet that builds and pushes sinker. Is this still being worked on?

**Comment by jpreese** [comment]
@eik3 sorry about that! The Dockerfile was made, but I never did the last couple of polishes I wanted to give it and push it up to the registry. I'll do that today.

**Comment by jpreese** [comment]
@eik3 sorry for the delay on this. [v0.14.0](https://github.com/plexsystems/sinker/releases/tag/v0.14.0) has been released and the corresponding Docker image has been pushed to DockerHub. The image (and future images) can be found at https://hub.docker.com/repository/docker/plexsystems/sinker

**Comment by eik3** [comment]
Thanks @jpreese! 

```
$ docker run --rm -it plexsystems/sinker --version
sinker version v0.14.0
```
:tada:
