### ISSUE TITLE
Validate all images can be pulled before attempting to pull

### ISSUE THREAD

**Issue by ravens** [plexsystems/sinker#38]
For any reason, if the pull process is experiencing some network issues on downloading a specific image, the whole process is getting interrupted. This could be problematic for CI environment. I am proposing some [PR](https://github.com/plexsystems/sinker/pull/37) to don't block but still emit an error during the execution.

**Comment by jpreese** [comment]
Thanks for opening this issue @ravens. The scenario definitely isn't ideal. 

Rather than logging an error during the pull operation, what are your thoughts on first verifying that you can successfully pull _all_ images in the manifest? We could just call [ImageExistsAtRemote](https://github.com/plexsystems/sinker/blob/main/internal/docker/docker.go#L172) on all of the images, and only pull them if all of the images are there. This would cover the case of invalid auth as well as if the image just didn't exist.

**Comment by ravens** [comment]
I think this makes sense ! I am just curious how this will handle intermittent network errors like the one I got the other day (which made me propose the PR actually) - the first call to check the image might work, but the second one might fail, right ?

**Comment by jpreese** [comment]
That is a fair point, theres no way to fully guarantee success due to network errors. That is the hope with Retry, to mitigate those (and they would hopefully be rare!). 

But this would prevent issues relating to authorization, which looks like was the problem from the error message in the PR

```text
7.4.2-SNAPSHOT: unauthorized: authentication required
```

**Comment by ravens** [comment]
So checking image presence and access makes sense. Perhaps a flag to have some blocking or non blocking behavior is more useful to cover interactive and non-interactive usages

**Comment by jpreese** [comment]
@ravens in [v0.14.0](https://github.com/plexsystems/sinker/releases/tag/v0.14.0) sinker will now pre-emptively check that it can pull all of the images before executing the pull command.
